-- Manual copy/paste migration. Do not auto-run. Replaces the product-only prototype.
begin;
drop table if exists public.refund_items,public.refunds,public.sale_items,public.sales,public.suspended_sale_items,public.suspended_sales,public.barcode_products,public.manual_products,public.categories,public.app_settings,public.app_owner cascade;
drop sequence if exists public.receipt_number_seq;

create table public.app_owner(singleton boolean primary key default true check(singleton),user_id uuid not null unique references auth.users(id) on delete restrict,created_at timestamptz not null default now());
create function public.is_app_owner() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from app_owner where user_id=auth.uid())$$;
create function public.claim_app_ownership() returns void language plpgsql security definer set search_path=public as $$begin if auth.uid() is null then raise exception 'Authentication required'; end if; insert into app_owner(user_id) values(auth.uid()); exception when unique_violation then if not is_app_owner() then raise exception 'Owner already registered'; end if; end$$;

create table public.app_settings(
 singleton boolean primary key default true check(singleton),store_name text not null default '' check(length(store_name)<=80),store_address text not null default '' check(length(store_address)<=140),store_phone text not null default '' check(length(store_phone)<=40),receipt_footer text not null default '' check(length(receipt_footer)<=140),timezone text not null default 'Asia/Baghdad' check(timezone='Asia/Baghdad'),theme text not null default 'dark' check(theme in('dark','light')),global_low_stock numeric(15,3) not null default 1 check(global_low_stock>=0),printer_enabled boolean not null default false,printer_name text not null default '' check(length(printer_name)<=120),paper_width smallint not null default 80 check(paper_width in(58,80)),print_margin_mm numeric(3,1) not null default 2 check(print_margin_mm between 0 and 5),print_feed_mm numeric(4,1) not null default 8 check(print_feed_mm between 0 and 30),receipt_font_size smallint not null default 12 check(receipt_font_size between 10 and 16),drawer_kick_after_cash_print boolean not null default true,drawer_reasons text[] not null default '{}',refund_reasons text[] not null default '{}',updated_at timestamptz not null default now());
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique check(length(trim(name)) between 1 and 24),color text not null check(color~'^#[0-9A-Fa-f]{6}$'),display_order smallint not null unique check(display_order between 1 and 13),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.manual_products(id uuid primary key default gen_random_uuid(),name text not null check(length(trim(name)) between 1 and 120),category_id uuid not null references categories(id) on delete restrict,unit_label text not null check(length(trim(unit_label)) between 1 and 30),selling_price bigint not null check(selling_price>=0),purchase_cost bigint not null check(purchase_cost>=0),stock_quantity numeric(15,3) not null default 0 check(stock_quantity>=0),is_favorite boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.barcode_products(id uuid primary key default gen_random_uuid(),barcode text not null unique check(barcode~'^[0-9]{4,32}$'),name text not null check(length(trim(name)) between 1 and 120),unit_label text not null check(length(trim(unit_label)) between 1 and 30),selling_price bigint not null check(selling_price>=0),purchase_cost bigint not null check(purchase_cost>=0),stock_quantity numeric(15,3) not null default 0 check(stock_quantity>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.suspended_sales(id uuid primary key default gen_random_uuid(),discount_type text check(discount_type in('percent','fixed')),discount_value bigint check(discount_value>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check((discount_type is null)=(discount_value is null)));
create table public.suspended_sale_items(id uuid primary key default gen_random_uuid(),suspended_sale_id uuid not null references suspended_sales(id) on delete cascade,item_type text not null check(item_type in('manual_product','barcode_product','manual_entry')),manual_product_id uuid references manual_products(id) on delete set null,barcode_product_id uuid references barcode_products(id) on delete set null,name text not null,unit_label text not null,quantity numeric(15,3) not null check(quantity>0),unit_price bigint not null check(unit_price>=0),unit_cost bigint check(unit_cost>=0),discount_type text check(discount_type in('percent','fixed')),discount_value bigint check(discount_value>=0),display_order integer not null check(display_order>=0),check((discount_type is null)=(discount_value is null)));

create sequence public.receipt_number_seq as bigint start 325100 minvalue 325100 maxvalue 999999 no cycle;
create table public.sales(id uuid primary key default gen_random_uuid(),receipt_number bigint not null unique default nextval('receipt_number_seq') check(receipt_number between 325100 and 999999),payment_method text not null check(payment_method in('cash','card')),subtotal bigint not null check(subtotal>=0),discount_type text check(discount_type in('percent','fixed')),discount_value bigint check(discount_value>=0),discount_amount bigint not null default 0 check(discount_amount>=0),total bigint not null check(total>=0),tendered bigint check(tendered>=0),change_due bigint not null default 0 check(change_due>=0),completed_at timestamptz not null default now(),check((discount_type is null)=(discount_value is null)),check(payment_method='cash' or(tendered is null and change_due=0)));
create table public.sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references sales(id) on delete restrict,item_type text not null check(item_type in('manual_product','barcode_product','manual_entry')),manual_product_id uuid references manual_products(id) on delete set null,barcode_product_id uuid references barcode_products(id) on delete set null,product_name text not null,unit_label text not null,quantity numeric(15,3) not null check(quantity>0),unit_price bigint not null check(unit_price>=0),unit_cost bigint check(unit_cost>=0),gross_amount bigint not null check(gross_amount>=0),discount_type text check(discount_type in('percent','fixed')),discount_value bigint check(discount_value>=0),discount_amount bigint not null default 0 check(discount_amount>=0),net_amount bigint not null check(net_amount>=0),display_order integer not null check(display_order>=0),check((discount_type is null)=(discount_value is null)));
create table public.refunds(id uuid primary key default gen_random_uuid(),sale_id uuid not null references sales(id) on delete restrict,reason text not null check(length(trim(reason)) between 1 and 120),payment_method text not null check(payment_method in('cash','card')),total bigint not null check(total>0),refunded_at timestamptz not null default now());
create table public.refund_items(id uuid primary key default gen_random_uuid(),refund_id uuid not null references refunds(id) on delete restrict,sale_item_id uuid not null references sale_items(id) on delete restrict,quantity numeric(15,3) not null check(quantity>0),amount bigint not null check(amount>=0),unique(refund_id,sale_item_id));

create index manual_products_name_idx on manual_products(name); create index manual_products_category_idx on manual_products(category_id); create index barcode_products_name_idx on barcode_products(name); create index sales_completed_idx on sales(completed_at desc); create index sale_items_sale_idx on sale_items(sale_id); create index refunds_sale_idx on refunds(sale_id); create index refund_items_line_idx on refund_items(sale_item_id);
create function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create trigger settings_touch before update on app_settings for each row execute function touch_updated_at(); create trigger categories_touch before update on categories for each row execute function touch_updated_at(); create trigger manual_touch before update on manual_products for each row execute function touch_updated_at(); create trigger barcode_touch before update on barcode_products for each row execute function touch_updated_at(); create trigger suspended_touch before update on suspended_sales for each row execute function touch_updated_at();
create function public.guard_refund_quantity() returns trigger language plpgsql as $$declare sold numeric(15,3);returned numeric(15,3);begin select quantity into sold from sale_items where id=new.sale_item_id; select coalesce(sum(quantity),0) into returned from refund_items where sale_item_id=new.sale_item_id and id<>new.id; if sold is null or returned+new.quantity>sold then raise exception 'Refund quantity exceeds sold quantity';end if;return new;end$$;
create trigger refund_quantity_guard before insert or update on refund_items for each row execute function guard_refund_quantity();

alter table app_owner enable row level security; alter table app_settings enable row level security; alter table categories enable row level security; alter table manual_products enable row level security; alter table barcode_products enable row level security; alter table suspended_sales enable row level security; alter table suspended_sale_items enable row level security; alter table sales enable row level security; alter table sale_items enable row level security; alter table refunds enable row level security; alter table refund_items enable row level security;
create policy owner_reads_owner on app_owner for select to authenticated using(user_id=auth.uid());
do $$declare t text;begin foreach t in array array['app_settings','categories','manual_products','barcode_products','suspended_sales','suspended_sale_items','sales','sale_items','refunds','refund_items'] loop execute format('create policy owner_all on %I for all to authenticated using(public.is_app_owner()) with check(public.is_app_owner())',t);end loop;end$$;
grant execute on function claim_app_ownership() to authenticated; grant usage,select on sequence receipt_number_seq to authenticated;
commit;
